on: push
name: Push
jobs:
  draftRelease:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Draft Release
        uses: toolmantim/release-drafter@v5.21.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6, 2.7 3.0, 3.1, 3.2, head]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test:units list
