on: push
name: Push
jobs:
  draftRelease:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Draft Release
        uses: release-drafter/release-drafter@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
